dependency-check:
  image: node:18
  stage: test
  script:
    - npm install -g dependency-guardian
    - dependency-guardian scan --include-dev --format json --output dependency-report.json
  artifacts:
    reports:
      json: dependency-report.json
  rules:
    - changes:
        - package.json
        - package-lock.json
        - yarn.lock 